apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      securityContext:
        fsGroup: 65534
      containers:
      - name: external-dns
        image: bitnami/external-dns:0.7.6
        args:
        - --source=service
        - --source=ingress
        - --domain-filter={{ .Values.domain_name }}
        - --provider=aws
        - --policy=sync
        - --registry=txt
        - --txt-owner-id={{ .Values.route53_zone_id }}
