{{- if index $.Values "apps" "external-dns-aws" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/external-dns-aws
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        external-dns-aws:
          {{- index .Values "external-dns-aws" | toYaml | nindent 10 }}
  destination:
    namespace: external-dns
    server: {{ .Values.spec.destination.server }}
  {{- if .Values.spec.syncPolicy }}
  syncPolicy:
    {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
  {{- end }}
{{- end }}
