---
apps:
  local-path-provisioner:
    enabled: true
  loki-stack:
    enabled: false
  metrics-server:
    enabled: false

argo-cd:
  server:
    extraArgs:
      - --insecure

cert-manager:
  tlsCrt: ${root_cert}
  tlsKey: ${root_key}

traefik:
  ports:
    web:
      hostPort: 80
    websecure:
      hostPort: 443
  service:
    type: NodePort
